// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs=true /home/jasonh/work/go/src/github.com/mistsys/tuntap/types_freebsd.go

package tuntap

const flagTruncated = 0
const ifreqSize = 0x20
const ifNameSize = 0x10
const in6AliasReqSize = 0x88
const in6SockAddrSize = 0x1c

const (
	SIOCDIFADDR_IN6 = 0x81206919
	SIOCAIFADDR_IN6 = 0x8088691b

	TUNSDEBUG  = 0x8004745a
	TUNGDEBUG  = 0x40047459
	TUNSIFINFO = 0x8008745b
	TUNGIFINFO = 0x4008745c
	TUNSLMODE  = 0x8004745d

	TUNSIFMODE = 0x8004745e
	TUNSIFPID  = 0x2000745f
	TUNSIFHEAD = 0x80047460
	TUNGIFHEAD = 0x40047461

	TAPSDEBUG  = 0x8004745a
	TAPGDEBUG  = 0x40047459
	TAPSIFINFO = 0x8008745b
	TAPGIFINFO = 0x4008745c

	TAPSVNETHDR = 0x8004745b
	TAPGVNETHDR = 0x4004745e
)
