// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs=true /home/jasonh/work/go/src/github.com/mistsys/tuntap/types_freebsd.go

package tuntap

const flagTruncated = 0
const ifreqSize = 0x20
const ifNameSize = 0x10

const (
	reqTUNSDEBUG  = 0x8004745a
	reqTUNGDEBUG  = 0x40047459
	eqTUNSIFINFO  = 0x8008745b
	reqTUNGIFINFO = 0x4008745c
	reqTUNSLMODE  = 0x8004745d

	reqTUNSIFMODE = 0x8004745e
	reqTUNSIFPID  = 0x2000745f
	reqTUNSIFHEAD = 0x80047460
	reqTUNGIFHEAD = 0x40047461

	reqTAPSDEBUG  = 0x8004745a
	reqTAPGDEBUG  = 0x40047459
	reqTAPSIFINFO = 0x8008745b
	reqTAPGIFINFO = 0x4008745c

	reqTAPSVNETHDR = 0x8004745b
	reqTAPGVNETHDR = 0x4004745e
)
